name: investigation
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Infrastructure.

  # state managment
  # https://pub.dev/packages/provider   
  provider: ^4.1.3

  # utility functions and classes in the style of dart:collection
  # https://pub.dev/packages/collection
  collection: ^1.14.12

  # http client
  # https://pub.dev/packages/chopper
  chopper: ^3.0.3  

  # defines the annotations used by json_serializable to create code for JSON serialization and deserialization
  # https://pub.dev/packages/json_annotation
  json_annotation: ^3.0.1

  # debugging and error logging
  # https://pub.dev/packages/logging
  logging: ^0.11.4

  # path provider for finding commonly used locations on the filesystem
  # https://pub.dev/packages/path_provider
  path_provider: ^1.6.11 

  # path manipulation
  # https://pub.dev/packages/path
  path: ^1.6.4

  # Internationalisation Support.

  flutter_localizations:
    sdk: flutter
  # provides internationalization and localization facilities, including message translation, 
  # plurals and genders, date/number formatting and parsing, and bidirectional text.
  # https://pub.dev/packages/intl     
  intl: 0.16.1    
  # enables obtaining localized locale names from locale codes (ISO 639‑2 and ISO 639-3) 
  # https://pub.dev/packages/flutter_localized_locales
  flutter_localized_locales: ^1.1.1

  # Device

  # camera
  # https://pub.dev/packages/camera
  # For android, change the minimum Android sdk version to 21 (or higher) in your android/app/build.gradle file.
  # On iOS, <key>NSCameraUsageDescription</key> has to be added inside ios/Runner/Info.plist in order the access the camera.   
  camera: ^0.5.8+2

  # Fonts

  # Allows you to easily use any of the 977 fonts (and their variants) from fonts.google.com
  # https://pub.dev/packages/google_fonts
  google_fonts: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  chopper_generator: ^3.0.4
  json_serializable: ^3.2.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: FontIcons
      fonts:
        - asset: fonts/MainIcons.ttf
